import "./globals.css";
import Navbar from "@/components/globals/navbar/Navbar";
import Provider from "@/components/Provider";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth/next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Necchange",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  console.log("Session", session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar session={session} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
