import "./globals.css";
import Navbar from "./components/globals/navbar/Navbar";
import Provider from "./components/Provider";
import {authOptions} from './lib/authOptions'
import { getServerSession } from "next-auth/next";

export const metadata = {
  title: "Necchange",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: {children: React.ReactNode;}) {
  const session = await getServerSession(authOptions)

  console.log("Session", session);
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar session={session}/>
          {children}
        </Provider>
      </body>
    </html>
  );
}