'use client'

import "./globals.css";
import Navbar from "./components/globals/navbar/Navbar";
import Provider from "./components/Provider";
import { useSession } from "next-auth/react";

export const metadata = {
  title: "Necchange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = useSession()

  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar session={session}/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
